### ISSUE TITLE
Can't Edit Accordion's "Click To Edit" section 

### ISSUE THREAD

**Issue by Deanphillips** [livecomposer/live-composer-page-builder#209] opened 2016-08-19 14:46 UTC
See attached

https://www.dropbox.com/s/80ri0ivs6sgv6i5/Screenshot%202016-08-19%2015.45.35.png?dl=0

Was also the same with many "Click To Edit" sections on the site (such as images)

**Comment by livecomposer** [comment] 2016-08-19 16:57
I think it's duplicate of #172 and it's already solved.

**Closed by livecomposer** 2016-08-19 16:57 UTC

**Comment by Deanphillips** [comment] 2016-08-19 17:41
It isn't resolved.

http://www.thesuperhumanlab.com/wp-admin/admin.php?page=livecomposer_editor&page_id=3287

On this page, it doesn't work (when I click on the text it just opens that accordion)

**Comment by livecomposer** [comment] 2016-08-19 18:07
You were right. It seems the previous patch were fixing only a few cases. I went though all the code and changed content editable properly. Should be working now.

**Comment by Deanphillips** [comment] 2016-08-19 19:21
Great! Any clue when the responsive issue I documented last week will be
looked at?!
